version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: fanfics
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flaskapp:
    build:
      context: back-end
      dockerfile: flask.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root   # Use the same user as MYSQL_ROOT_USER
      - DB_PASSWORD=${DB_PASSWORD}   # Use the same password as MYSQL_ROOT_PASSWORD
      - DB_NAME=fanfics

networks:
  backend:
    driver: bridge